var gp_editor=!1,debug_area;function debug(a){debug_area||(debug_area=$('<div id="debug" style="position:absolute;top:0;left:0;background:#fff;padding:10px;z-index:99999;border:1px solid #333;max-width:30%;white-space:pre-wrap">').prependTo("body"));debug_area.prepend("<div>"+LOGO(a)+"</div><hr/>")}
function LOGO(a){var b,c=typeof a,d="\n<br/> ("+c+") ";if("object"===c)for(b in a){if(a.hasOwnProperty(b)){d+="\n<b>"+b+"</b> = ";try{d+=$gp.htmlchars(a[b])}catch(g){d+=" -- not allowed -- "}}}else d+=$gp.htmlchars(a);return d}$gp.Coords=function(a){a.hasClass("inner_size")&&(a=a.children(":first"));var b=a.offset();b.w=a.outerWidth();b.h=a.outerHeight();return b};$gp.div=function(a){var b=$("#"+a);0===b.length&&(b=$('<div id="'+a+'"></div>').appendTo("#gp_admin_html"));return b};
$gp.links.iadmin_box=function(a,b){a.preventDefault();$gp.CopyVals(b,this);$gp.AdminBoxC($(b),"inline")};$gp.links.inline_edit_generic=function(a,b){a.preventDefault();$gp.loading();if("function"===typeof gplinks[b])gplinks[b].call(this,b,a);else{$gp.LoadStyle("/include/css/inline_edit.css");var c=strip_from(this.href,"#"),d=$(this).attr("id").substr(13);$.getScript(c+"&cmd=inlineedit&area_id="+d,function(a){"false"===a&&(alert($gp.error),$gp.loaded())})}};
$gp.links.remote=function(a){a.preventDefault();a=$gp.jPrep(this.href,"gpreq=body");if(gpRem){var b=window.location.href.split("/"),b=b[0]+"//"+b[2]+gpBase;0<window.location.href.indexOf("index.php")&&(b+="/index.php");a+="&inUrl="+encodeURIComponent(b)+"&gpRem="+encodeURIComponent(gpRem)}b=$(window).height()-130;$gp.AdminBoxC('<iframe src="'+a+'" style="height:'+b+'px;" frameborder="0" />',{context:"iframe",width:780})};
$gp.LoadStyle=function(a){var b=(new Date).getTime();$('<link rel="stylesheet" type="text/css" />').appendTo("head").attr({href:gpBase+a+"?t="+b})};
$gp.AdminBoxC=function(a,b){$gp.CloseAdminBox();if(""===a)return!1;"string"==typeof b?b={context:b}:"undefined"==typeof b&&(b={});b=$.extend({context:"",width:640},b);var c=$(window),d=b.width,g=Math.round((c.width()-d-40)/2),f=Math.max($(document).height(),$("body").outerHeight(!0));$gp.div("gp_admin_box1").css({zIndex:11E3,"min-height":f}).stop(!0,!0,!0).fadeTo(0,0).fadeTo(200,0.2);$gp.div("gp_admin_box").css({zIndex:"11001",left:g,top:c.scrollTop()}).stop(!0,!0,!0).fadeIn(400).html('<a class="gp_admin_box_close" data-cmd="admin_box_close"></a><div id="gp_admin_boxc" class="'+
(b.context||"")+'" style="width:'+d+'px"></div>').find("#gp_admin_boxc").html(a).find("input:visible:first").focus();$(".messages").detach();return!0};$gp.CloseAdminBox=function(a){a&&a.preventDefault();$("#gp_admin_box1").fadeOut();$("#gp_admin_box").fadeOut(300,function(){$("#gp_admin_boxc").hasClass("inline")?$("#gp_admin_boxc").children().appendTo("#gp_hidden"):$("#gp_admin_boxc").children().remove()});"undefined"!==typeof $.fn.colorbox&&$.fn.colorbox.close()};
$gp.links.admin_box_close=gpinputs.admin_box_close=$gp.CloseAdminBox;$gp.SaveGPUI=function(){if(isadmin){var a="do=savegpui";$.each(gpui,function(b,c){a+="&gpui_"+b+"="+c});$gp.postC(window.location.href,a)}};
$gp.links.dd_menu=function(a){a.preventDefault();a.stopPropagation();$(".messages").detach();var b=this,c=$(this).parent().find(".dd_list");c.show();if(c.find(".selected").length){a=c.find("ul:first");var d=c.find(".selected").prev().prev().prev().position();d&&a.scrollTop(d.top+a.scrollTop())}$("body").on("click.gp_select",function(a){c.hide();c.off(".gp_select");$("body").off(".gp_select");$(a.target).closest(b).length&&a.stopPropagation()})};
$gp.links.tabs=function(a){a.preventDefault();a=$(this);a.siblings("a").removeClass("selected").each(function(a,c){c.hash&&$(c.hash).hide()});this.hash&&(a.addClass("selected"),$(this.hash).show())};$gp.Loaded={};$gp.LoadScripts=function(a,b,c){function d(){g--;0===g&&"function"===typeof b&&b.call(this)}var g=a.length,f=(new Date).getTime(),h="";c&&(h=gpBase);$.each(a,function(a,b){b=h+b;$gp.Loaded[b]?d():($gp.Loaded[b]=!0,$.getScript($gp.jPrep(b,"t="+f),function(){d()}))})};
$gp.links.gp_refresh=function(a){a.preventDefault();$gp.Reload()};$gp.links.toggle_panel=function(a){var b=$("#simplepanel");a.preventDefault();var c="";b.hasClass("minb")?(c="",a=0):b.hasClass("compact")?(c="minb toggledmin",a=3):(c="compact",a=1);b.hasClass("toggledmin")||b.unbind("mouseenter touchstart").bind("mouseenter touchstart",function(a){b.unbind(a).removeClass("toggledmin")});b.attr("class","keep_viewable "+c);gpui.cmpct=a;$gp.SaveGPUI()};
$gp.links.toplink=function(){var a=$(this);if(!$("#simplepanel").hasClass("compact")){var b=a.next(),c=b.is(":visible")&&0<b.height();$("#simplepanel .panelgroup2:visible").slideUp(300);gpui.vis=!1;c||(gpui.vis=a.data("arg"),b.slideDown(300));$gp.SaveGPUI()}};
$gp.links.collapsible=function(){var a=$(this).parent();a.hasClass("one")&&a.hasClass("gp_collapsed")?(a.parent().find(".head").addClass("gp_collapsed"),a.parent().find(".collapsearea").slideUp(300),a.removeClass("gp_collapsed").next().slideDown(300)):a.toggleClass("gp_collapsed").next().slideToggle(300)};
$gp.links.ajax_box=$gp.links.admin_box=function(a){alert(' "ajax_box" and "admin_box" are deprecated link arguments. Use gpabox instead.');a.preventDefault();$gp.loading();a=$gp.jPrep(this.href,"gpreq=flush");$.get(a,"",function(a){$gp.AdminBoxC(a);$gp.loaded()},"html")};$gp.links.gpabox=function(a){a.preventDefault();$gp.loading();a=$gp.jPrep(this.href)+"&gpx_content=gpabox";$.getJSON(a,$gp.Response)};
$gp.links.add_table_row=function(a){a=$(this).closest("tr");var b=a.closest("tbody").find("tr:first").clone();b.find(".class_only").remove();b.find("input").val("");a.before(b)};$gp.inputs.gpabox=function(){return $gp.post(this,"gpx_content=gpabox")};$gp.inputs.gpcheck=function(){this.checked?$(this).parent().addClass("checked"):$(this).parent().removeClass("checked")};$gp.inputs.check_all=function(){$(this).closest("form").find("input[type=checkbox]").prop("checked",this.checked)};
$gp.inputs.cnreq=function(a){a.preventDefault();a=$(this.form).serialize();$gp.Cookie("cookie_cmd",encodeURIComponent(a),1);window.location=strip_from(strip_from(this.form.action,"#"),"?")};$gp.htmlchars=function(a){a=a||"";return $("<a>").text(a).html()};$gp.response.location=function(a){window.setTimeout(function(){window.location=a.SELECTOR},a.CONTENT)};
$(function(){function a(){var a=$("#admincontainer");1>a.length||($("#gpAfterContent").css("margin-top",a.height()+100),SimpleDrag("#admincontent_panel",a,"absolute",function(b){gpui.pposx=b.left;gpui.pposy=b.top;a.css({left:Math.max(5,gpui.pposx),top:Math.max(5,gpui.pposy)});$gp.SaveGPUI()}))}function b(){$("#current_page_panel").bind("mouseenter.edb touchstart.edb",function(){var a=0,b,c=$(window),e=$("#editable_areas_list").html("");b=$gp.div("gp_edit_box");$("a.ExtraEditLink").clone(!1).attr("class",
"").css("display","block").show().each(function(){var d,p,l;p=$(this);var n=p.attr("id").substr(13);l=$("#ExtraEditArea"+n);if(l.hasClass("gp_no_overlay")||0===l.length)return!0;a++;d=this.title.replace(/_/g," ");d=decodeURIComponent(d);15<d.length&&(d=d.substr(0,14)+"...");p.attr("id","editable_mark"+n).text(d).appendTo(e).wrap("<li>").on("mouseenter touchstart",function(){var a=$gp.Coords(l);b.stop(!0,!0,!0).css({top:a.top-3,left:a.left-2,width:a.w+4,height:a.h+5}).fadeIn();(c.scrollTop()>a.top||
c.scrollTop()+c.height()<a.top)&&$("html,body").stop(!0,!0,!0).animate({scrollTop:Math.max(0,a.top-100)},"slow")}).on("mouseleave touchend",function(){b.stop(!0,!0,!0).fadeOut()}).click(function(){$(this).unbind("mouseenter touchstart");window.setTimeout(function(){$(this).remove();b.hide()},100)})})})}function c(){function a(b){b&&(b.hasClass("gp_editing")||b.removeClass("gp_no_overlay"))}function b(){if(m&&!s){var a=m.offset(),e=m.position(),c=$(window).scrollTop(),a=Math.max(0,c-(a.top-e.top));
m.stop(!0,!0,!0).animate({top:a})}}function c(){l&&window.clearTimeout(l);l=window.setTimeout(function(){e()},200)}function e(){k=!1;n.find("span").stop(!0,!0).hide(500);n.find("div").stop(!0,!0).fadeOut()}function d(a){var e;if(!a.hasClass("gp_no_overlay")){e=a.attr("id").substr(13);var c=$("#ExtraEditLnks"+e).find("a");if(0===c.length&&(c=$("#ExtraEditLink"+e),0===c.length))return;e=$gp.Coords(a);n.show().css({top:e.top-3,left:e.left-2,width:e.w+6});m?m.stop(!0,!0).show().removeClass("gp_hover"):
(m=$("<span>"),r=$("<div>"),n.html(r).append(m));r.stop(!0,!0).hide().css({height:e.h+5,width:e.w+4});b();c=c.clone(!0).removeClass("ExtraEditLink");s=!1;m.css({left:"auto",top:0,right:0,position:"absolute"}).html('<a class="gp_overlay_expand"></a>').append(c).unbind("mouseenter touchstart").one("mouseenter touchstart",function(){a.hasClass("gp_no_overlay")||p()})}}function p(){m.addClass("gp_hover").stop(!0,!0).show();r.stop(!0,!0).fadeIn()}var l=!1,n,m=!1,k,r,s=!1;n=$gp.div("gp_edit_overlay");n.click(function(a){var b=
$(a.target);0<b.filter("a").length&&(b.hasClass("gp_overlay_close")&&a.preventDefault(),k&&k.addClass("gp_no_overlay"));e()}).on("mouseleave touchend",function(){c()}).on("mouseenter touchstart",function(){l&&window.clearTimeout(l)});$(".editable_area").bind("mousemove.gp mouseenter.gp touchstart.gp",function(b){l&&window.clearTimeout(l);var e=$(this);0<e.parent().closest(".editable_area").length&&b.stopPropagation();k&&e.attr("id")===k.attr("id")||(k&&a(k),k=e,d(k))}).bind("mouseleave touchend",
function(){c();a(k)});$(window).scroll(function(){b()});$(document).on("contextmenu",".editable_area, #gp_edit_overlay",function(a){if(!(a.ctrlKey||a.altKey||a.shiftKey||gp_editor)&&m){a.preventDefault();var b=$(window);p();var e=a.pageX-b.scrollLeft(),c=e+m.width()-b.width();0<c&&(e-=c);m.css({top:a.pageY-b.scrollTop(),left:e,right:"auto",position:"fixed"});s=!0}})}function d(){SimpleDrag("#simplepanel .toolbar, #simplepanel .toolbar a","#simplepanel","fixed",function(a){gpui.tx=a.left;gpui.ty=a.top;
$gp.SaveGPUI()},!0);admin_resizable?SimpleResize("#admincontainer",{min_w:300,finish:function(a,b){gpui.pposx=b;gpui.pw=a;$gp.SaveGPUI()}}):$("#admincontainer").css("width","auto");$(".in_window").parent().bind("mouseenter touchstart",function(){var a=$(this).children(".in_window").css({right:"auto",left:"100%",top:0});window.setTimeout(function(){var b=a.offset(),c=b.left+a.width(),b=b.top+a.height(),e=$(window);c>e.width()+e.scrollLeft()&&a.css({right:"100%",left:"auto"});c=e.height()+e.scrollTop();
b>c&&a.css({top:c+-b-10})},1)})}$(document).on("mousedown","form",function(){var a=$(this);"checked"!==a.data("gpForms")&&("undefined"!==typeof this["return"]&&(this["return"].value=window.location),a.data("gpForms","checked"))});isadmin&&"undefined"===typeof gp_bodyashtml&&(a(),$("body").addClass("gpAdmin").trigger("AdminReady"),window.setTimeout(function(){c();b();d()},500),$(document).on("keyup keypress paste change",".show_character_count",function(){$(this).parent().find(".character_count span").html(this.value.length)}),
$(window).on("beforeunload",function(){if(gp_editor&&"undefined"!==typeof gp_editor.checkDirty&&gp_editor.checkDirty())return"Unsaved changes will be lost."}))});
function SimpleDrag(a,b,c,d){function g(a,b){if(a.hasClass("keep_viewable")){var c="fixed"===a.css("position"),d,k={};d=a.position();c&&(d.left-=e.scrollLeft(),d.top-=e.scrollTop());if(b)a.data({gp_left:d.left,gp_top:d.top});else if(c=a.data("gp_left"))d.left=k.left=c,d.top=k.top=a.data("gp_top");var c=a.width(),h=e.height();d.top<f?k.top=f:d.top>h&&(k.top=h+2*f);c=e.width()-c-f;d.left>c&&(k.left=c);(k.left||k.top)&&a.css(k)}}var f=-10,h=$(b),e=$(window),q=$(document);$(document).off("mousedown.sdrag",
a).on("mousedown.sdrag",a,function(a){function b(){var c=h.offset();m=a.clientX-c.left+e.scrollLeft();k=a.clientY-c.top+e.scrollTop()}if(1==a.which){var n,m,k;a.preventDefault();if(!(1>h.length))return b(),q.bind("mousemove.sdrag",function(a){if(!n){var b=h.offset(),c=h.width(),e=h.height();n=$gp.div("admin_drag_box").css({top:b.top,left:b.left,width:c,height:e})}n.css({left:Math.max(f,a.clientX-m),top:Math.max(f,a.clientY-k)});a.preventDefault();return!1}),q.unbind("mouseup.sdrag").bind("mouseup.sdrag",
function(a){var b,g,l;q.unbind("mousemove.sdrag mouseup.sdrag");if(!n)return!1;a.preventDefault();n.remove();n=!1;b=a.clientX-m;g=a.clientY-k;"absolute"===c&&(b+=e.scrollLeft(),g+=e.scrollTop());b=Math.max(f,b);g=Math.max(f,g);l={left:b,top:g};h.css(l).data({gp_left:b,gp_top:g});"function"===typeof d&&d.call(h,l,a);return!1}),!1}});"fixed"!==h.css("position")&&"fixed"!==h.parent().css("position")||g(h.addClass("keep_viewable"),!0);e.resize(function(){$(".keep_viewable").each(function(){g($(this),
!1)})})}
$gp.response.renameprep=function(){function a(){h.val().replace(/_/g," ").toLowerCase()!==f?$("#gp_rename_redirect").show(500):$("#gp_rename_redirect").hide(300)}function b(a){a.preventDefault();a=$(this).closest("td");var b=a.find("a:visible");a.find("a").show();b.hide();b=a.find("a:visible");b.length&&(b.hasClass("slug_edit")?(a.find("input").addClass("sync_label").prop("disabled","disabled").fadeTo(400,0.6),c()):a.find("input").removeClass("sync_label").prop("disabled","").fadeTo(400,1))}function c(){var b=
$("input.title_label").val();$("input.new_title.sync_label").val(d(b));$("input.browser_title.sync_label").val(b);a();return!0}function d(a){a=a.replace(/[\x00-\x1F\x7F]/g,"");a=a.replace(/(\?|\*|:|#)/g,"");a=a.replace(/(<(\/?[a-zA-Z0-9][^<>]*)>)/ig,"");a=a.replace(/[\\]/g,"/");a=a.replace(/^\.+[\/\/]/,"/");a=a.replace(/[\/\/]\.+$/,"/");a=a.replace(/[\/\/]\.+[\/\/]/g,"/");a=a.replace(/[\/\/]+/g,"/");a="."===a?"":a.replace(/^\/\/*/g,"");return a.replace(/ /g,"_")}var g,f,h;(function(){g=$("#gp_rename_form");
f=g.find("input[name=old_title]").val().toLowerCase();h=$("input.new_title");c();$("input[disabled=disabled]").each(function(a,b){$(b).fadeTo(400,0.6)});$("input.title_label").bind("keyup change",c);$(".label_synchronize a").click(b);$gp.links.showmore=function(){$("#gp_rename_table tr").show(500);$(this).parent().remove()};h.bind("keyup change",function(){a()})})()};
function SimpleResize(a,b){b=$.extend({},{max_w:1E4,min_w:0,finish:function(a,b){}},b);var c=$(a);if(!(1>c.length))$('<span class="gp_admin_resize"></span><span class="gp_admin_resize gp_resize_right"></span>').appendTo(c).on("mousedown.sres",function(a){if(1==a.which){var g=a.clientX,f=c.width(),h=f,e=c.position().left,q=e,p=$(this).hasClass("gp_resize_right"),l=new Date;a.preventDefault();$('<div style="position:fixed;top:0;right:0;bottom:0;left:0;cursor:e-resize;z-index:999000;">').appendTo("body").on("mousemove.sres",
function(a){var d=new Date;if(!(200>d-l))return l=d,p?f=a.clientX-g+h:(e=a.clientX-g+q,f=g-a.clientX+h,e=Math.max(0,e),c.css({left:e})),f=Math.min(b.max_w,f),f=Math.max(b.min_w,f),c.width(f).resize(),!1}).off("mouseup.sres").on("mouseup.sres",function(a){a.preventDefault();$(this).off("mousemove.sres mouseup.sres").remove();b.finish.call(c,f,e);return!1});return!1}})}
"function"!==typeof $.fn.disableSelection&&($.fn.disableSelection=function(){return $(this).attr("unselectable","on").css("-moz-user-select","none").each(function(){this.onselectstart=function(){return!1}})},$.fn.enableSelection=function(){return $(this).attr("unselectable","off").css("-moz-user-select","").each(function(){this.onselectstart=function(){return!1}})});