var $gp={inputs:{},response:{},error:"There was an error processing the last request. Please reload this page to continue.",jGoTo:function(a){$gp.loading();a=$gp.jPrep(a);$.getJSON(a,$gp.Response)},cGoTo:function(a,c){var d=$(a),d=a.search+"&verified="+encodeURIComponent(d.data("nonce"));$gp.Cookie("cookie_cmd",encodeURIComponent(d),1);c?$gp.Reload():window.location=strip_from(strip_from(a.href,"#"),"?")},post:function(a,c){$gp.loading();var d=$(a).closest("form"),b=d.serialize()+"&verified="+encodeURIComponent(post_nonce);
if("INPUT"===a.nodeName||"BUTTON"===a.nodeName)b+="&"+encodeURIComponent(a.name)+"="+encodeURIComponent(a.value);c&&(b+="&"+c);$.post($gp.jPrep(d.attr("action")),b,$gp.Response,"json");return!1},post_link:function(a){$gp.loading();var c=$(a),c=strip_to(a.search,"?")+"&gpreq=json&jsoncallback=?&verified="+encodeURIComponent(c.data("nonce"));$.post(strip_from(a.href,"?"),c,$gp.Response,"json")},postC:function(a,c,d,b){d=d||$gp.Response;b=b||"json";"object"===typeof c&&(c=$.param(c));c+="&verified="+
encodeURIComponent(post_nonce);"json"===b&&(c+="&gpreq=json&jsoncallback=?");$.post(strip_from(a,"?"),c,d,b)},cboxSettings:function(a){a=a||{};colorbox_lang=colorbox_lang||{};return $.extend(colorbox_lang,{opacity:0.75,maxWidth:"90%",maxHeight:"90%"},a)},Cookie:function(a,c,d){var b="";d&&(b=new Date,b.setTime(b.getTime()+864E5*d),b="; expires="+b.toGMTString());document.cookie=a+"="+c+b+"; path=/"},jPrep:function(a,c){c="undefined"===typeof c?"gpreq=json&jsoncallback=?":c;a=strip_from(a,"#");a+=
-1===a.indexOf("?")?"?":"&";return a+c},Response:function(a,c,d){$(".messages").detach();try{$gp.CloseAdminBox()}catch(b){}try{$.fn.colorbox.close()}catch(e){}$.each(a,function(a,b){if("function"===typeof $gp.response[b.DO])$gp.response[b.DO].call(this,b,c,d);else if("function"===typeof gpresponse[b.DO])gpresponse[b.DO].call(this,b,c,d);else{switch(b.DO){case "replace":$(b.SELECTOR).replaceWith(b.CONTENT);break;case "inner":$(b.SELECTOR).html(b.CONTENT);break;case "admin_box_data":$gp.AdminBoxC(b.CONTENT);
break;case "messages":$(b.CONTENT).appendTo("body").show().css({top:0})}var e=$(b.SELECTOR);if("function"==typeof e[b.DO])e[b.DO](b.CONTENT)}});$gp.loaded()},loading:function(){$("#loading1").css("zIndex",99E3).fadeTo(1,0.3).next().css("zIndex",99001).show()},loaded:function(){$("#loading1, #loading2").clearQueue().hide()},CopyVals:function(a,c){var d=$(a).find("form").get(0);d&&$(c).find("input").each(function(c,a){d[a.name]&&(d[a.name].value=a.value)})},Reload:function(){typeof req_type&&"post"==
req_type?window.location.href=strip_from(window.location.href,"#"):window.location.reload(!0)},links:{gallery:function(a,c){a.preventDefault();c=""===c?this:"a[rel="+c+"],a."+c;$.colorbox.remove();$(c).colorbox($gp.cboxSettings({resize:!0,rel:c}));$.colorbox.launch(this)}}};$gp.Cookie("cookie_cmd","",-1);
$(function(){function a(c){$(c).filter("[method=post]").append('<input type="hidden" name="verified" value="'+post_nonce+'" />')}$("body").addClass("STCLASS");$(document).ajaxError(function(c,a,b,e){$gp.loaded();"abort"!=a.statusText&&"function"!==typeof b.error&&""!=e&&("undefined"===typeof debugjs&&alert($gp.error),c={thrownError:e,responseText:a.responseText,responseStatus:a.status,statusText:a.statusText,url:b.url,type:b.type,browser:navigator.userAgent},window.console&&console.log&&console.log(c),
!0===debugjs&&"function"===typeof debug&&(b.data&&(c.data=b.data.substr(0,100)),debug(c)),"send"===debugjs&&(alert($gp.error),b.data&&(c.data=b.data),c.cmd="javascript_error",$.ajax({type:"POST",url:"http://www.gpeasy.com/Resources",data:c,success:function(){},error:function(){}})))});$(document).on("click","input,button",function(c){a(this.form);var d=$(this);if(!d.hasClass("gpvalidate")||"function"!=typeof this.form.checkValidity||this.form.checkValidity()){var b=d.data("cmd");b||(b=strip_from(d.attr("class"),
" "));if("function"===typeof $gp.inputs[b])return $gp.inputs[b].call(this,c);if("function"===typeof gpinputs[b])return gpinputs[b].call(this,c,c);switch(b){case "gppost":case "gpajax":return $gp.post(this)}return!0}});$(document).on("submit","form",function(){a(this)});$(document).delegate(".expand_child",{mouseenter:function(){var a=$(this).addClass("expand");a.hasClass("simple_top")&&a.addClass("simple_top_hover")},mouseleave:function(){$(this).removeClass("expand simple_top_hover")}});$(document).on("click",
"a",function(a){var d=$(this),b=d.data("cmd"),e=d.data("arg");b||(b=d.attr("name"),e=d.attr("rel"));if(d.hasClass("gpconfirm")&&!confirm(this.title))a.preventDefault();else{if("function"===typeof $gp.links[b])return $gp.links[b].call(this,a,e);if("function"===typeof gplinks[b])return gplinks[b].call(this,e,a);switch(b){case "toggle_show":$(e).toggle();break;case "inline_box":$gp.CopyVals(e,this);$.fn.colorbox($gp.cboxSettings({inline:!0,href:e,open:!0}));break;case "postlink":$gp.post_link(this);
break;case "gpajax":$gp.jGoTo(this.href);break;case "creq":$gp.cGoTo(this,!0);break;case "cnreq":$gp.cGoTo(this,!1);break;case "close_message":d.closest("div").slideUp();break;default:return!0}a.preventDefault();return!1}});$("body").trigger("gpReady")});function strip_to(a,c){if(!a)return a;var d=a.indexOf(c);return-1<d?a.substr(d+1):a}function strip_from(a,c){if(!a)return a;var d=a.indexOf(c);0<d&&(a=a.substr(0,d));return a}function jPrep(a,c){return $gp.jPrep(a,c)}
function ajaxResponse(a,c,d){return $gp.Response(a,c,d)}function loading(){$gp.loading()}function loaded(){$gp.loaded()};